### ISSUE TITLE
token失效，刷新token导致报错

### ISSUE THREAD

**Issue by fengzhao** [Hidove/aliyundrive-uploader#28]
检索目录中
AccessToken已失效，尝试刷新AccessToken中
refresh_token已经失效
refresh_token已经失效
Traceback (most recent call last):
  File "main.py", line 105, in <module>
  File "main.py", line 63, in distribute_thread
  File "main.py", line 52, in thread
  File "Client.py", line 167, in upload_file
  File "AliyunDrive.py", line 291, in get_parent_folder_id
  File "AliyunDrive.py", line 275, in create_folder
  File "AliyunDrive.py", line 334, in check_auth
  File "AliyunDrive.py", line 115, in token_refresh
  File "AliyunDrive.py", line 109, in token_refresh
  File "requests/models.py", line 900, in json
  File "json/__init__.py", line 346, in loads
  File "json/decoder.py", line 337, in decode
  File "json/decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 1)
[562590] Failed to execute script 'main' due to unhandled exception!
root@Server-4bae148c-dd03-4cfe-ae72-f2f61e41420d:/usr/local/src/ali#
root@Server-4bae148c-dd03-4cfe-ae72-f2f61e41420d:/usr/local/src/ali#

**Comment by aoaostar** [comment]
嗯，token失效任务也没办法继续下去了啊，我就直接raise了，也可以`common.suicide()`正常退出
