### ISSUE TITLE
上传中出现错误

### ISSUE THREAD

**Issue by seeblog** [Hidove/aliyundrive-uploader#47]
win10 编译版本

Traceback (most recent call last):
  File "main.py", line 51, in <module>
  File "common.py", line 161, in print_info
  File "common.py", line 208, in log
UnicodeEncodeError: 'gbk' codec can't encode character '\u200b' in position 69: illegal multibyte sequence

[4044] Failed to execute script 'main' due to unhandled exception!

**Comment by aoaostar** [comment]
https://github.com/Hidove/aliyundrive-uploader/blob/d5de2fc24855b63bac427e5055e49f66b1a6f1dd/common.py#L208
改成
```
    with open(file, 'a',encoding'utf-8') as f:
```

**Comment by seeblog** [comment]
解决了 谢谢！
