### ISSUE TITLE
开始上传后报错

### ISSUE THREAD

**Issue by zsbai** [Hidove/aliyundrive-uploader#5]
检索目录中
目录id获取成功60898fee4524df8614d74fa6a9df689e35b4ea0a
正在上传:   1%|1                         | 53.0M/6.84G [00:30<1:06:53, 1.82MB/s]
Traceback (most recent call last):
  File "/root/aliyundrive-uploader/main.py", line 137, in <module>
    if res.result():
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 438, in result
    return self.__get_result()
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 390, in __get_result
    raise self._exception
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/root/aliyundrive-uploader/main.py", line 61, in upload_file
    drive.upload(upload_url)
  File "/root/aliyundrive-uploader/AliyunDrive.py", line 117, in upload
    res.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://bj29.cn-beijing.data.alicloudccp.com/xYBXOEkb%2F69848%2F608991ae51a2863ccd5b466b8bf84ab711c83d46%2F608991ae11f21bbc22964fbbaf08e0f2fca9d24f?Expires=1619632062&OSSAccessKeyId=LTAIsE5mAn2F493Q&Signature=IUxxWsQ36QnVxA0W%2FnwWESNHsfs%3D&partNumber=1&uploadId=658982D766A74E5AB6BB7D64A564C38C

**Comment by zsbai** [comment]
发现了，上传30s必出错，小于30s时间的小文件可以正常上传

**Comment by Hidove** [comment]
@zsbai 
我尝试了20GB文件上传，发现阿里云盘最大上传文件大小仅支持5G
之前我上传win10的镜像文件4.9G
![image](https://user-images.githubusercontent.com/42663943/116539248-27b02b00-a91b-11eb-919a-150aac576ba8.png)
```
<?xml version="1.0" encoding="UTF-8"?>\n<Error>\n  <Code>EntityTooLarge</Code>\n  <Message>Your proposed upload exceeds the maximum allowed size.</Message>\n  <RequestId>608A8DA331A03432376BC7F3</RequestId>\n  <HostId>bj29.cn-beijing.data.alicloudccp.com</HostId>\n  <MaxSizeAllowed>5368709120</MaxSizeAllowed>\n  <ProposedSize>20971520000</ProposedSize>\n</Error>
```

**Comment by zsbai** [comment]
网页端是可以上传超5g的东西呀....

**Comment by Hidove** [comment]
不知道诶，我之前上传了14GB的视频都没有问题
但是现在不行了，应该是之前没限制现在限制了吧
![image](https://user-images.githubusercontent.com/42663943/116551331-6a2d3400-a92a-11eb-8408-cbc031f229b3.png)

**Comment by zsbai** [comment]
我是6gb的镜像文件，在网页端上传也没有提示超过限制什么的...

**Comment by Hidove** [comment]
我重新看了一下官方的，是做了分块上传的，每块最大5G，我更新了一下，已经OK了，执行更新命令即可
![image](https://user-images.githubusercontent.com/42663943/116606053-c2802800-a962-11eb-9fcc-fce5a3d9bf61.png)

**Comment by zsbai** [comment]
检索目录中
目录id获取成功60898fee4524df8614d74fa6a9df689e35b4ea0a
正在上传: 100%|####| 6.84G/6.84G [33:34<00:00, 3.65MB/s]Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.9/dist-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.9/dist-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.9/http/client.py", line 1345, in getresponse
    response.begin()
  File "/usr/lib/python3.9/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.9/http/client.py", line 276, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.9/dist-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.9/dist-packages/urllib3/util/retry.py", line 532, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.9/dist-packages/urllib3/packages/six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.9/dist-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.9/dist-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.9/dist-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.9/http/client.py", line 1345, in getresponse
    response.begin()
  File "/usr/lib/python3.9/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.9/http/client.py", line 276, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/aliyundrive-uploader/main.py", line 116, in <module>
    if res.result():
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 438, in result
    return self.__get_result()
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 390, in __get_result
    raise self._exception
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/root/aliyundrive-uploader/main.py", line 43, in upload_file
    drive.upload(part_info_list)
  File "/root/aliyundrive-uploader/AliyunDrive.py", line 126, in upload
    res = requests.put(
  File "/usr/lib/python3/dist-packages/requests/api.py", line 134, in put
    return request('put', url, data=data, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
root@vultr:~/aliyundrive-uploader# 
上传完成后报错，阿里云盘里没有发现上传文件....

**Comment by Hidove** [comment]
这个问题已经解决了，不知道迭代器哪里有问题，搞了半天，换了个写法，阔以了~
我测试个9.89G和1.10G文件上传
![image](https://user-images.githubusercontent.com/42663943/116749356-6507dc00-aa33-11eb-94cd-e1228ee650ce.png)
![image](https://user-images.githubusercontent.com/42663943/116753688-0eea6700-aa3a-11eb-9310-3a3627ade60d.png)
![image](https://user-images.githubusercontent.com/42663943/116753749-288bae80-aa3a-11eb-8309-0cc4082fec0b.png)

**Comment by zsbai** [comment]
万分感谢🙏
